### ISSUE TITLE
Is this possible with ESP32 ?

### ISSUE THREAD

**Issue by happytm** [FrodgE/sun-harvester#1]
I just found your excellent work. I am trying to make a fixed target heliostat using ESP32 hardware. Is it possible using this code ?

Thanks.

**Comment by FrodgE** [comment]
It is indeed!  I have been doing further development on both ESP32 & ESP8266, check out the "unofficial" branch:
https://github.com/FrodgE/sun-harvester/tree/unofficial

Not sure if you read over the readme etc but I can't take any credit for this project.  I took the existing open source code, and have been cleaning it up a little to suit my own needs & preferences (WIP) and then shared back to the community in case others found it of value.  I've kept my changes on the "unofficial" branch.

Happy tinkering!  Cheers, Michael.

**Comment by happytm** [comment]
I see it now.

Thanks.
